# -*- coding: utf-8 -*-
"""海流_(0703_日).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RhQmePGOVtaOxmKlaGjYoYpr7u4fi78f
"""

from google.colab import drive
drive.mount('/content/drive')   # 會跳出授權連結

import os, requests

# 指定下載後要存到 Drive 裡的路徑
base_drive = '/content/drive/MyDrive/data'
os.makedirs(base_drive, exist_ok=True)

# 下載 .nc
nc_url = "https://cwaopendata.s3.ap-northeast-1.amazonaws.com/Model/M-B0071-000.nc"
nc_path = os.path.join(base_drive, "M-B0071-000.nc")
r = requests.get(nc_url, stream=True)
r.raise_for_status()
with open(nc_path, 'wb') as f:
    for chunk in r.iter_content(8192):
        f.write(chunk)

# 下載 .grb2 系列
grib_base = "https://cwaopendata.s3.ap-northeast-1.amazonaws.com/Model/M-A0064-"
for i in range(0, 85, 6):
    url = f"{grib_base}{i:03d}.grb2"
    out = os.path.join(base_drive, f"M-A0064-{i:03d}.grb2")
    r = requests.get(url, stream=True)
    r.raise_for_status()
    with open(out, 'wb') as f:
        for chunk in r.iter_content(8192):
            f.write(chunk)

print("✅ 全部檔案已儲存到 Google Drive:data 資料夾")

import os
import requests

# ── 設定 ──
# NetCDF 檔案 URL 與存放路徑
nc_url = "https://cwaopendata.s3.ap-northeast-1.amazonaws.com/Model/M-B0071-000.nc"
nc_dir = "./nc_files/"
nc_local = os.path.join(nc_dir, "M-B0071-000.nc")

# GRIB2 檔案參數
grib_base = "https://cwaopendata.s3.ap-northeast-1.amazonaws.com/Model/M-A0064-"
start, end, step = 0, 84, 6
grib_dir = "./grib2_files/"

# ── 建立資料夾 ──
os.makedirs(nc_dir, exist_ok=True)
os.makedirs(grib_dir, exist_ok=True)

# ── 下載 NetCDF ──
print(f"正在下載 NetCDF：{nc_url}")
try:
    r = requests.get(nc_url, stream=True, timeout=30)
    r.raise_for_status()
    with open(nc_local, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            if chunk:
                f.write(chunk)
    print(f"✅ NetCDF 儲存到：{nc_local}")
except Exception as e:
    print(f"❌ NetCDF 下載失敗：{e}")

# ── 下載 GRIB2 系列檔案 ──
for i in range(start, end+1, step):
    url = f"{grib_base}{i:03d}.grb2"
    local = os.path.join(grib_dir, f"M-A0064-{i:03d}.grb2")
    print(f"正在下載：{url}")
    try:
        r = requests.get(url, stream=True, timeout=30)
        r.raise_for_status()
        with open(local, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
        print(f"✅ 成功儲存：{local}")
    except Exception as e:
        print(f"❌ 無法下載 {url}：{e}")

# Commented out IPython magic to ensure Python compatibility.
!apt update
!apt install -y wget build-essential nco
!wget https://www.ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2.tgz
!tar -xvzf wgrib2.tgz
# %cd wgrib2
!make
!cp wgrib2/wgrib2 /usr/local/bin/
!wgrib2 -v

!pip install numpy
!pip install matplotlib
!pip install requests
!pip install netCDF4
!pip install cmocean

# OpenDrift 模型與相關依賴
!pip install opendrift
!pip install pyproj

# 地圖繪製
!pip install cartopy
!pip install gdal

# 解析 XML
!pip install lxml

# 可選：必要時支援 NetCDF、GRIB2 轉換
!pip install nco

docker pull opendrift/opendrift

! mamba create -n opendrift python=3 opendrift
! conda activate opendrift

# 安裝 conda 到 Colab 環境中
!pip install -q condacolab
import condacolab
condacolab.install()

# 安裝 wgrib2 套件（使用 conda-forge）
!mamba install -c conda-forge wgrib2 -y

!mamba install -c conda-forge wgrib2 -y

import os
import subprocess

os.makedirs("nc_parts", exist_ok=True)

for file in os.listdir("grib2_files"):
    if file.endswith(".grb2"):
        grib_path = f"grib2_files/{file}"
        nc_path = f"nc_parts/{file.replace('.grb2', '.nc')}"
        print(f"轉換中：{file} → {nc_path}")
        cmd = ["wgrib2", grib_path, "-netcdf", nc_path]
        subprocess.run(cmd, check=True)

!pip install -q condacolab
import condacolab
condacolab.install()

"""安裝opendrift

"""

# 安裝 mamba（conda 的加速版本）
!conda install -c conda-forge mamba -y

# 安裝 opendrift + gdal + cartopy + 所有依賴
!mamba install -c conda-forge opendrift gdal cartopy -y

!pip install xarray netCDF4

!pip uninstall -y pyproj
!pip install pyproj --upgrade

from opendrift.models.leeway import Leeway
from opendrift.readers.reader_netCDF_CF_generic import Reader
print("✅ OpenDrift 模組載入成功！")

Current_ds = xr.open_dataset("C:\Users\WIN\Desktop\current_fixed.nc")
list(Current_ds.data_vars)

Wind_ds = xr.open_dataset("C:\Users\WIN\Desktop\current_fixed.nc")
list(Wind_ds .data_vars)

import xarray as xr



# 開啟原始風場資料


# 將 UGRD_100mb / VGRD_100mb 改名為 OpenDrift 能讀的標準變數
Wind_ds = Current_ds.rename({
    'UC': 'x_wind',
    'VC': 'y_wind'
})

# 加上必要的座標屬性（確保有 time, latitude, longitude）
for var in ['x_wind', 'y_wind']:
    Wind_ds[var].attrs['standard_name'] = 'eastward_wind' if var == 'x_wind' else 'northward_wind'
    Wind_ds[var].attrs['units'] = 'm s-1'
    Wind_ds[var].attrs['coordinates'] = 'longitude latitude'

# 儲存為新的風場檔案
ds.to_netcdf('/content/wind_fixed.nc')

import xarray as xr

# 開啟原始海流 NetCDF
ds = xr.open_dataset('/content/nc_files/M-B0071-000.nc')

# 檢查是否包含 UC / VC
assert 'UC' in ds and 'VC' in ds, "找不到 UC/VC 變數"

# 重新命名變數
ds = ds.rename({
    'UC': 'x_sea_water_velocity',
    'VC': 'y_sea_water_velocity'
})

# 加上 CF 標準屬性（OpenDrift 必要）
ds['x_sea_water_velocity'].attrs.update({
    'standard_name': 'eastward_sea_water_velocity',
    'units': 'm s-1',
    'coordinates': 'longitude latitude'
})
ds['y_sea_water_velocity'].attrs.update({
    'standard_name': 'northward_sea_water_velocity',
    'units': 'm s-1',
    'coordinates': 'longitude latitude'
})

# 儲存轉換後檔案
output_path = '/content/current_fixed.nc'
ds.to_netcdf(output_path)
print(f'✅ 已儲存為 {output_path}')

import shutil

# 設定目標資料夾（可自行修改）
target_dir = '/content/drive/MyDrive/simulation_outputs/'

# 建立資料夾（若不存在）
import os
os.makedirs(target_dir, exist_ok=True)

# 複製檔案
shutil.copy('/content/current_fixed.nc', target_dir)
shutil.copy('/content/wind_fixed.nc', target_dir)

print("檔案已成功儲存至 Google Drive。")

from datetime import timedelta, datetime
import cmocean
from opendrift.models.leeway import Leeway
from opendrift.readers import reader_netCDF_CF_generic

# 初始化 Leeway 模型
o = Leeway(loglevel=20)

# 讀入風場與海流資料（皆為已重新命名的 NetCDF）
reader_wind = reader_netCDF_CF_generic.Reader('/content/wind_fixed.nc')         # 應含 x_wind, y_wind
reader_current = reader_netCDF_CF_generic.Reader('/content/current_fixed.nc')   # 應含 x_sea_water_velocity, y_sea_water_velocity
o.add_reader([reader_wind, reader_current])

# 模擬備援設定（可選，避免缺資料報錯）
o.set_config('environment:fallback:x_sea_water_velocity', 0)
o.set_config('environment:fallback:y_sea_water_velocity', 0)
o.set_config('environment:fallback:x_wind', 0)
o.set_config('environment:fallback:y_wind', 0)
# 1️⃣ 建立一个带 PlateCarree 投影的 Figure/Axis

# 設定漂流物類型與投放條件
object_type = 26  # 26 = Life raft, no ballast
o.seed_elements(
    lon=119.1, lat=24.0,               # 台灣東部海域
    number=500,                        # 投放數量
    radius=1000,                       # 隨機半徑（公尺）
    time=reader_wind.start_time,       # 投放時間取自風場資料起始
    object_type=object_type
)

# 執行模擬：48 小時，每 30 分鐘計算一次，每小時輸出一次
ds = o.run(duration=timedelta(hours=12), time_step=1800, time_step_output=3600)

# 畫出模擬動畫（背景：海流）
o.animation(
    background=['x_sea_water_velocity', 'y_sea_water_velocity'],
    skip=5,
    cmap=cmocean.cm.speed,
    vmin=0,
    vmax=0.8,
    bgalpha=0.7,
    land_color='#666666',
    fast=True
)

# 靜態最終軌跡圖
o.plot(fast=True)